-- MySQL Script generated by MySQL Workbench
-- sam 13 jan 2018 20:43:45 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema wordoff
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wordoff` ;

-- -----------------------------------------------------
-- Schema wordoff
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wordoff` DEFAULT CHARACTER SET utf8mb4 ;
USE `wordoff` ;

-- -----------------------------------------------------
-- User for wordoff
-- -----------------------------------------------------
CREATE USER 'wordoffuser'@'localhost' IDENTIFIED BY 'wordoffpass'; -- Creates the user
GRANT ALL ON WordOff.* TO 'wordoffuser'@'localhost'; -- Gives all the privileges to the new user on the newly created database

-- -----------------------------------------------------
-- Table `wordoff`.`player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordoff`.`player` ;

CREATE TABLE IF NOT EXISTS `wordoff`.`player` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `wordoff`.`ai`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordoff`.`ai` ;

CREATE TABLE IF NOT EXISTS `wordoff`.`ai` (
  `id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FKppamqja2oifefw563wfsry7xl`
    FOREIGN KEY (`id`)
    REFERENCES `wordoff`.`player` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `wordoff`.`side`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordoff`.`side` ;

CREATE TABLE IF NOT EXISTS `wordoff`.`side` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `answer_counter` SMALLINT(6) NOT NULL,
  `challenge` LONGBLOB NULL DEFAULT NULL,
  `player_rack` LONGBLOB NULL DEFAULT NULL,
  `score` INT(11) NOT NULL,
  `wordanalyser` BIT(1) NOT NULL,
  `player_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKnp6qrawkhr82t3gc9ybr0gcqh` (`player_id` ASC),
  CONSTRAINT `FKnp6qrawkhr82t3gc9ybr0gcqh`
    FOREIGN KEY (`player_id`)
    REFERENCES `wordoff`.`player` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `wordoff`.`answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordoff`.`answer` ;

CREATE TABLE IF NOT EXISTS `wordoff`.`answer` (
  `num` SMALLINT(6) NOT NULL,
  `challenge` LONGBLOB NULL DEFAULT NULL,
  `side_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`num`, `side_id`),
  INDEX `FKobtqoo2eu8wbrdypbmgmvw7va` (`side_id` ASC),
  CONSTRAINT `FKobtqoo2eu8wbrdypbmgmvw7va`
    FOREIGN KEY (`side_id`)
    REFERENCES `wordoff`.`side` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `wordoff`.`mode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordoff`.`mode` ;

CREATE TABLE IF NOT EXISTS `wordoff`.`mode` (
  `dtype` VARCHAR(31) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `lang` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `start_date` TINYBLOB NULL DEFAULT NULL,
  `type` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `wordoff`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordoff`.`game` ;

CREATE TABLE IF NOT EXISTS `wordoff`.`game` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `bag` LONGBLOB NULL DEFAULT NULL,
  `ended` BIT(1) NOT NULL,
  `start_date` TINYBLOB NULL DEFAULT NULL,
  `curr_player_id` BIGINT(20) NULL DEFAULT NULL,
  `mode_id` BIGINT(20) NULL DEFAULT NULL,
  `side_init_id` BIGINT(20) NULL DEFAULT NULL,
  `side_resp_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK6s1uxa5abxem7g58h8twyrjil` (`curr_player_id` ASC),
  INDEX `FKq2rn2hdqw2pgx20orc28kl68l` (`mode_id` ASC),
  INDEX `FKiqnk445svrtiuyigl13qi7ic2` (`side_init_id` ASC),
  INDEX `FKer5l5j5kcf6s8cwvq6ehhgb09` (`side_resp_id` ASC),
  CONSTRAINT `FK6s1uxa5abxem7g58h8twyrjil`
    FOREIGN KEY (`curr_player_id`)
    REFERENCES `wordoff`.`player` (`id`),
  CONSTRAINT `FKer5l5j5kcf6s8cwvq6ehhgb09`
    FOREIGN KEY (`side_resp_id`)
    REFERENCES `wordoff`.`side` (`id`),
  CONSTRAINT `FKiqnk445svrtiuyigl13qi7ic2`
    FOREIGN KEY (`side_init_id`)
    REFERENCES `wordoff`.`side` (`id`),
  CONSTRAINT `FKq2rn2hdqw2pgx20orc28kl68l`
    FOREIGN KEY (`mode_id`)
    REFERENCES `wordoff`.`mode` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `wordoff`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordoff`.`user` ;

CREATE TABLE IF NOT EXISTS `wordoff`.`user` (
  `coins` INT(11) NOT NULL,
  `login` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `last_notifs_recup` TINYBLOB NULL DEFAULT NULL,
  `level` INT(11) NOT NULL,
  `id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FKp23d49isj1h8qfx7sjmpa2u0m`
    FOREIGN KEY (`id`)
    REFERENCES `wordoff`.`player` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `wordoff`.`invitation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordoff`.`invitation` ;

CREATE TABLE IF NOT EXISTS `wordoff`.`invitation` (
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `target_id` BIGINT(20) NOT NULL,
  `mode_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`mode_id`, `target_id`),
  INDEX `FK7hdwihi6nkphjr3448wesg88j` (`target_id` ASC),
  CONSTRAINT `FK7hdwihi6nkphjr3448wesg88j`
    FOREIGN KEY (`target_id`)
    REFERENCES `wordoff`.`user` (`id`),
  CONSTRAINT `FKo5s4n13bmkmt3kdctcgighsg1`
    FOREIGN KEY (`mode_id`)
    REFERENCES `wordoff`.`mode` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `wordoff`.`lang_set`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordoff`.`lang_set` ;

CREATE TABLE IF NOT EXISTS `wordoff`.`lang_set` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `wordoff`.`letter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordoff`.`letter` ;

CREATE TABLE IF NOT EXISTS `wordoff`.`letter` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `lang_set_id` INT(11) NULL DEFAULT NULL,
  `score` INT(11) NOT NULL,
  `value` CHAR(1) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKf64vmekm7al78h9r0jg48q69r` (`lang_set_id` ASC),
  CONSTRAINT `FKf64vmekm7al78h9r0jg48q69r`
    FOREIGN KEY (`lang_set_id`)
    REFERENCES `wordoff`.`lang_set` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 54
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `wordoff`.`notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordoff`.`notification` ;

CREATE TABLE IF NOT EXISTS `wordoff`.`notification` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `date` TINYBLOB NULL DEFAULT NULL,
  `target_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKbo9iww48qpdrlmkd08qgvtypv` (`target_id` ASC),
  CONSTRAINT `FKbo9iww48qpdrlmkd08qgvtypv`
    FOREIGN KEY (`target_id`)
    REFERENCES `wordoff`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `wordoff`.`relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordoff`.`relation` ;

CREATE TABLE IF NOT EXISTS `wordoff`.`relation` (
  `status` INT(11) NULL DEFAULT NULL,
  `target_id` BIGINT(20) NOT NULL,
  `owner_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`owner_id`, `target_id`),
  INDEX `FK1jsx5ceoh0vh855ebdvq7cc88` (`target_id` ASC),
  CONSTRAINT `FK1jsx5ceoh0vh855ebdvq7cc88`
    FOREIGN KEY (`target_id`)
    REFERENCES `wordoff`.`user` (`id`),
  CONSTRAINT `FKe9967yi3pd7790emidb5ig3xy`
    FOREIGN KEY (`owner_id`)
    REFERENCES `wordoff`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `wordoff`.`tile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordoff`.`tile` ;

CREATE TABLE IF NOT EXISTS `wordoff`.`tile` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `lang_set_id` INT(11) NULL DEFAULT NULL,
  `letter_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKt4ggomh6o3fcgt7rm22buwjcs` (`letter_id` ASC),
  INDEX `FKhctaa32o0u4w3dmksqis70e37` (`lang_set_id` ASC),
  CONSTRAINT `FKhctaa32o0u4w3dmksqis70e37`
    FOREIGN KEY (`lang_set_id`)
    REFERENCES `wordoff`.`lang_set` (`id`),
  CONSTRAINT `FKt4ggomh6o3fcgt7rm22buwjcs`
    FOREIGN KEY (`letter_id`)
    REFERENCES `wordoff`.`letter` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 223
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
